#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# CREATE FINAL PATH
#=================================================
ynh_script_progression "Creating final path..."

mkdir -p "$install_dir/$app/sites/all/modules"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE DRUSH ALIAS
#=================================================
ynh_script_progression "Creating Drush alias..."

#mkdir -p "$install_dir/.drush"
#ynh_config_add --template="yoursite.aliases.drushrc.php" --destination="$install_dir/.drush/$app.aliases.drushrc.php"

#copied from drupal
mkdir -p "$install_dir/drush/sites/"
ynh_config_add --template="example.site.yml" --destination="$install_dir/drush/sites/$app.site.yml"

#=================================================
# INSTALL COMPOSER
#=================================================
ynh_script_progression "Installing Composer..."

mkdir -p "$install_dir/.composer"
ynh_config_add --template="composer.json" --destination="$install_dir/composer.json"
ynh_composer_install --phpversion="$php_version" --workdir="$install_dir" --composerversion="$composer_version"
ynh_composer_exec install


ynh_composer_install
ynh_composer_exec install --no-dev

#export PATH="$install_dir/.composer/vendor/bin:$PATH"
export PATH="$install_dir/vendor/bin:$PATH"

#=================================================
# INSTALL DRUPAL AND CIVICRM
#=================================================
ynh_script_progression "Installing Drupal and CiviCRM..."

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"


pushd "$install_dir"
#    _ynh_exec_with_drush_php drush pm-download -y drupal-7 --drupal-project-rename="$app"

    _ynh_exec_drush site-install "$install_profil" \
        --account-name="$admin" --account-pass="$password" --account-mail="$admin_mail" \
        --db-url="mysql://$db_user:$db_pwd@localhost/$db_name" --site-name="$app" --locale="$language" --yes
chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"
    #_ynh_exec_drush pm-download drush_language
    #_ynh_exec_drush pm-download ldap
    #_ynh_exec_drush pm-enable -y ldap_servers ldap_user ldap_authentication ldap_authorization ldap_authorization_drupal_role
    #_ynh_exec_drush pm-download l10n_update
    #_ynh_exec_drush pm-enable -y l10n_update
    #_ynh_exec_drush language-add "$language"
    #_ynh_exec_drush language-default "$language"
    #_ynh_exec_drush cache-clear drush
    #_ynh_exec_drush l10n-update-refresh
    #_ynh_exec_drush l10n-update
    #_ynh_exec_drush pm-update
    #_ynh_exec_drush core-cron

    #ynh_setup_source --dest_dir="$install_dir/$app/sites/all/modules/civicrm" --source_id="civicrm-drupal"
    #ynh_setup_source --dest_dir="$install_dir/$app/sites/all/modules/civicrm" --source_id="civicrm-l10n"

    #touch "$install_dir/$app/sites/default/civicrm.settings.php"

    #chmod 750 "$install_dir"
    #chmod -R o-rwx "$install_dir"
    #chown -R "$app:www-data" "$install_dir"

    #_ynh_exec_drush --include="$install_dir/$app/sites/all/modules/civicrm/drupal/drush" civicrm-install \
    #    --dbhost="localhost" --dbname="$db_name" --dbpass="$db_pwd" --dbuser="$db_user" --destination="sites/all/modules" --site_url="$domain$path" --ssl=on
    cv core:install -n --cwd=$install_dir/$app --cms-base-url="http://$domain$path" --db="mysql://$db_user:$db_pwd@localhost:3306/$db_name"
    ln -s $install_dir/libraries $install_dir/$app/libraries
    chmod 750 "$install_dir"
    chmod -R o-rwx "$install_dir"
    chown -R "$app:www-data" "$install_dir"

popd

ynh_store_file_checksum $install_dir/$app/sites/default/settings.php
ynh_store_file_checksum $install_dir/$app/sites/default/civicrm.settings.php

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm
# Create a dedicated NGINX config
ynh_config_add_nginx
# Create a Cron job
ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
